#port
server:
  port: 80


spring:
  #database
  datasource:
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  #redis
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        #连接池最大连接数
        max-active: 8
        #连接池最大等待阻塞时间（负数表示没有限制）
        max-wait: -1
        #连接池最大空闲连接
        max-idle: 5
        #连接池最小空闲连接
        min-idle: 0
    #连接超时时间（ms）
    timeout: 10000

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.woniu.springboot.model

#show sql
logging:
  level:
    com.woniu.springboot.mapper: DEBUG

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: false
